### ISSUE TITLE
Invalid csrf token error when editing a location

### ISSUE THREAD

**Issue by corbindk** [versx/WhMgr-UI#53]
```
ForbiddenError: invalid csrf token
    at csrf (/home/whmgr/testui/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/whmgr/testui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/whmgr/testui/node_modules/express/lib/router/index.js:317:13)
    at /home/whmgr/testui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/whmgr/testui/node_modules/express/lib/router/index.js:335:12)
    at next (/home/whmgr/testui/node_modules/express/lib/router/index.js:275:10)
    at cookieParser (/home/whmgr/testui/node_modules/cookie-parser/index.js:71:5)
    at Layer.handle [as handle_request] (/home/whmgr/testui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/whmgr/testui/node_modules/express/lib/router/index.js:317:13)
    at /home/whmgr/testui/node_modules/express/lib/router/index.js:284:7
```

Editing other types of settings works. can delete locations and add new ones fine.

**Comment by versx** [comment]
Looks like I forgot to implement the `/api/location/edit/:id` route.
